const arenasData = [
  { "id": 1, "name": "Estádio Goblin", "min_trophies": 0 },
  { "id": 2, "name": "Poço dos Ossos", "min_trophies": 300 },
  { "id": 3, "name": "Torneio Bárbaro", "min_trophies": 600 },
  { "id": 4, "name": "Vale dos Feitiços", "min_trophies": 1000 },
  { "id": 5, "name": "Oficina do Construtor", "min_trophies": 1300 },
  { "id": 6, "name": "Parquinho da P.E.K.K.A", "min_trophies": 1600 },
  { "id": 7, "name": "Arena Real", "min_trophies": 2000 },
  { "id": 8, "name": "Pico Congelado", "min_trophies": 2300 },
  { "id": 9, "name": "Arena da Selva", "min_trophies": 2600 },
  { "id": 10, "name": "Montanha do Porco", "min_trophies": 3000 },
  { "id": 11, "name": "Vale Elétrico", "min_trophies": 3400 },
  { "id": 12, "name": "Cidade Assombrada", "min_trophies": 3800 },
  { "id": 13, "name": "Esconderijo do Patife", "min_trophies": 4200 },
  { "id": 14, "name": "Pico da Serenidade", "min_trophies": 4600 },
  { "id": 15, "name": "Mina do Mineiro", "min_trophies": 5000 },
  { "id": 16, "name": "Cozinha do Executor", "min_trophies": 5500 },
  { "id": 17, "name": "Cripta Real", "min_trophies": 6000 },
  { "id": 18, "name": "Santuário Silencioso", "min_trophies": 6500 },
  { "id": 19, "name": "Spa do Dragão", "min_trophies": 7000 },
  { "id": 20, "name": "Campo de Treinamento", "min_trophies": 7500 },
  { "id": 21, "name": "Clash Fest", "min_trophies": 8000 },
  { "id": 22, "name": "PANQUECAS!", "min_trophies": 8500 },
  { "id": 23, "name": "Valkalla", "min_trophies": 9000 },
  { "id": 24, "name": "Arena Lendária", "min_trophies": 9500 },
  { "id": 25, "name": "Cabana do Lenhador", "min_trophies": 10000 },
  { "id": 26, "name": "Estrada Real", "min_trophies": 10500 },
  { "id": 27, "name": "Rua da Mosqueteira", "min_trophies": 11000 },
  { "id": 28, "name": "Pico dos Heróis", "min_trophies": 11500 },
  { "id": 29, "name": "Escola Mágica", "min_trophies": 12000 },
  { "id": 30, "name": "Arena do Clash Supremo", "min_trophies": 12500 },
  { "id": 31, "name": "Taverna do Pequeno Príncipe", "min_trophies": 13000 },
  { "id": 32, "name": "Praça dos Espíritos", "min_trophies": 13500 },
  ];
